server:
  debug: true
  host: "0.0.0.0" # Current machine ip
  port: 5000

database:
  host: "localhost"
  name: "naochallenge23"
  user: "postgres"
  password: "postgres"

weather_api:
  api_key: ""
  latitude: ""
  longitude: ""